version: '3.8'

services:
  frontend:
    build:
      context: .
      target: development
    container_name: consulting-gpt-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_VERSION=v1
    networks:
      - consulting-gpt-network

networks:
  consulting-gpt-network:
    name: consulting-gpt-network
